name: flutter_design
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.1.2 #phone call
  english_words: 3.1.5 #A package containing the most ~5000 used English words and some utility functions.
  permission_handler: 5.0.1+1 #This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  speech_recognition: ^0.3.0 #A flutter plugin to use the speech recognition iOS10+ / Android 4.1+ link: https://github.com/rxlabz/speech_recognition
  introduction_screen: 1.0.9 # Introduction screen allow you to have a screen at launcher for example, where you can explain your app.
  carousel_slider: 2.2.1 #A carousel slider widget for flutter
  http: 0.12.2 #A composable, Future-based library for making HTTP requests.
  internet_speed_test: 1.1.2+1 #Internet speed test plugin to integrate it in your app whenever you want.
  signal_strength_indicator: 0.3.0+1
  toast: 0.1.5 #For display toast message
  syntax_highlighter: 0.1.1 #Highlighting syntax in code snippets for code recipes
  animated_floatactionbuttons: ^0.1.0 #To provide Floating Action widget to zoom in and out code snippet text


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/collapse_toolbar.jpg
    - assets/images/online_Ad.png
    - assets/images/online_article.png
    - assets/images/shared_workspace.png
    - assets/images/website.png
    - lib/pdf/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
